# Generated by Django 3.0.3 on 2020-08-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istiak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='Istiak.Tag'),
        ),
    ]
