# Generated by Django 3.0.3 on 2020-08-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Istiak', '0002_auto_20200827_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Istiak.Tag'),
        ),
    ]
